using System;
using System.Collections.Generic;

namespace DemoApp.DataGrid;

/// <summary>
/// The demo's words in its two languages: the pages' names and descriptions, the column captions, the plans and statuses, the status
/// lines under the grids, the page's own buttons and tooltips, and in the second language every framework, code field and grid word
/// it registers, so the missing-word report in Development names only a real gap (DemoWordsCoverageTests). The sections' prose and
/// the data are left as written on purpose: under <see cref="KeyPrefix"/> they are content.
/// </summary>
internal static class DataGridDemoWords
{
    /// <summary>What every key of the demo starts with; every other string is content (<c>KeyPrefixes</c>).</summary>
    public const string KeyPrefix = "grid-demo.";

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["grid-demo.column.subscription"] = "Subscription",
        ["grid-demo.column.customer"] = "Customer",
        ["grid-demo.column.country"] = "Country",
        ["grid-demo.column.plan"] = "Plan",
        ["grid-demo.column.status"] = "Status",
        ["grid-demo.column.usage"] = "Usage",
        ["grid-demo.column.servers"] = "Servers",
        ["grid-demo.column.monthly"] = "Monthly",
        ["grid-demo.column.started"] = "Started",
        ["grid-demo.column.paid"] = "Paid",

        ["grid-demo.plan.starter"] = "Starter",
        ["grid-demo.plan.standard"] = "Standard",
        ["grid-demo.plan.pro"] = "Pro",
        ["grid-demo.plan.dedicated"] = "Dedicated",

        ["grid-demo.status.trial"] = "Trial",
        ["grid-demo.status.active"] = "Active",
        ["grid-demo.status.past-due"] = "Past due",
        ["grid-demo.status.suspended"] = "Suspended",
        ["grid-demo.status.cancelled"] = "Cancelled by the customer",

        ["grid-demo.page.columns"] = "Columns and editing",
        ["grid-demo.page.columns.description"] = "A grid from NE.Standard.UI.DataGrid over thirty subscriptions the page holds whole: sort by header, move a column, edit a cell, open a row's detail.",
        ["grid-demo.page.filters"] = "Filters and totals",
        ["grid-demo.page.filters.description"] = "A hundred and twenty subscriptions the page holds whole: sort, search and filters run in the browser, and the footer adds up what they leave.",
        ["grid-demo.page.source"] = "A large source",
        ["grid-demo.page.source.description"] = "The same columns over a windowed source of a hundred thousand subscriptions: the source sorts, narrows and adds up, and hands back the window on show.",

        ["grid-demo.code"] = "Code",
        ["grid-demo.copy"] = "Copy",
        ["grid-demo.detail.per-server"] = "Per server, monthly",

        ["grid-demo.edited"] = "{number}: {column} is now {value}.",
        ["grid-demo.columns.cells-edit"] = "Cells edit",
        ["grid-demo.columns.download"] = "Download CSV",
        ["grid-demo.columns.delete-chosen"] = "Delete chosen",
        ["grid-demo.columns.edit-hint"] = "Double-click a cell, or press F2 on the keyboard's row, to edit it.",
        ["grid-demo.columns.row-gone"] = "Row {id} is not on the page.",
        ["grid-demo.columns.selection-hint"] = "Tick a row to choose it; the button appears once something is chosen.",
        ["grid-demo.columns.none-chosen"] = "Nothing chosen.",
        ["grid-demo.columns.chosen.one"] = "{count} subscription of {total} chosen.",
        ["grid-demo.columns.chosen.other"] = "{count} subscriptions of {total} chosen.",
        ["grid-demo.filters.hint"] = "A click chooses a row and shows its detail; a double click opens it, even on a cell the first page edits.",
        ["grid-demo.filters.chosen"] = "{number} chosen.",
        ["grid-demo.filters.opened"] = "{number} opened.",
        ["grid-demo.source.past-due"] = "Past due, from €100 a month",
        ["grid-demo.source.no-filters"] = "No filters",
        ["grid-demo.source.not-asked"] = "The source has not been asked for anything but its first window.",
        ["grid-demo.source.edit-hint"] = "Double-click a cell to edit it: the write goes through the source, which keeps it and reads the subscription anew.",
        ["grid-demo.source.row-gone"] = "Row {id} is not in either window.",
        ["grid-demo.source.no-terms.one"] = "No terms: the source answers in its own order, {rows} row.",
        ["grid-demo.source.no-terms.other"] = "No terms: the source answers in its own order, {rows} rows.",
        ["grid-demo.source.matches.one"] = "{terms} — {rows} row matches, read on the server.",
        ["grid-demo.source.matches.other"] = "{terms} — {rows} rows match, read on the server."
    };

    // The framework ships English only; an application brings every other language, the framework's and the packages' words too.
    // Chinese has one plural form, so a plural key has only its ".other".
    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        ["grid-demo.column.subscription"] = "订阅",
        ["grid-demo.column.customer"] = "客户",
        ["grid-demo.column.country"] = "国家",
        ["grid-demo.column.plan"] = "套餐",
        ["grid-demo.column.status"] = "状态",
        ["grid-demo.column.usage"] = "用量",
        ["grid-demo.column.servers"] = "服务器",
        ["grid-demo.column.monthly"] = "月费",
        ["grid-demo.column.started"] = "开始日期",
        ["grid-demo.column.paid"] = "已付",

        ["grid-demo.plan.starter"] = "入门版",
        ["grid-demo.plan.standard"] = "标准版",
        ["grid-demo.plan.pro"] = "专业版",
        ["grid-demo.plan.dedicated"] = "专属版",

        ["grid-demo.status.trial"] = "试用",
        ["grid-demo.status.active"] = "有效",
        ["grid-demo.status.past-due"] = "逾期",
        ["grid-demo.status.suspended"] = "已暂停",
        ["grid-demo.status.cancelled"] = "客户已取消",

        ["grid-demo.page.columns"] = "列与编辑",
        ["grid-demo.page.columns.description"] = "NE.Standard.UI.DataGrid 的表格，列出页面完整持有的三十个订阅：按表头排序、移动列、编辑单元格、打开行的详情。",
        ["grid-demo.page.filters"] = "筛选与合计",
        ["grid-demo.page.filters.description"] = "页面完整持有的一百二十个订阅：排序、搜索和筛选都在浏览器中进行，表尾汇总筛选后剩下的行。",
        ["grid-demo.page.source"] = "大型数据源",
        ["grid-demo.page.source.description"] = "同样的列，基于十万个订阅的窗口化数据源：由数据源排序、筛选和汇总，并返回当前显示的窗口。",

        ["grid-demo.code"] = "代码",
        ["grid-demo.copy"] = "复制",
        ["grid-demo.detail.per-server"] = "每台服务器月费",

        ["grid-demo.edited"] = "{number}：{column} 现为 {value}。",
        ["grid-demo.columns.cells-edit"] = "单元格可编辑",
        ["grid-demo.columns.download"] = "下载 CSV",
        ["grid-demo.columns.delete-chosen"] = "删除所选",
        ["grid-demo.columns.edit-hint"] = "双击单元格，或在键盘所在行按 F2，即可编辑。",
        ["grid-demo.columns.row-gone"] = "第 {id} 行不在此页上。",
        ["grid-demo.columns.selection-hint"] = "勾选一行即可选中；选中后会出现按钮。",
        ["grid-demo.columns.none-chosen"] = "未选择任何订阅。",
        ["grid-demo.columns.chosen.other"] = "已选择 {count} 个订阅，共 {total} 个。",
        ["grid-demo.filters.hint"] = "单击一行即可选中并显示其详情；双击则打开该行，即使双击的是首页中可编辑的单元格。",
        ["grid-demo.filters.chosen"] = "已选择 {number}。",
        ["grid-demo.filters.opened"] = "已打开 {number}。",
        ["grid-demo.source.past-due"] = "逾期，每月 €100 起",
        ["grid-demo.source.no-filters"] = "无筛选",
        ["grid-demo.source.not-asked"] = "数据源除首个窗口外尚未被请求。",
        ["grid-demo.source.edit-hint"] = "双击单元格即可编辑：写入经由数据源，数据源保存后重新读取该订阅。",
        ["grid-demo.source.row-gone"] = "第 {id} 行不在任一窗口中。",
        ["grid-demo.source.no-terms.other"] = "没有条件：数据源按自身顺序返回 {rows} 行。",
        ["grid-demo.source.matches.other"] = "{terms} — 服务器上有 {rows} 行匹配。",

        ["ui.grid.yes"] = "是",
        ["ui.grid.no"] = "否",
        ["ui.grid.sort-by"] = "按{column}排序",
        ["ui.grid.filter"] = "筛选",
        ["ui.grid.from"] = "从",
        ["ui.grid.to"] = "到",
        ["ui.grid.any"] = "任意",
        ["ui.grid.search"] = "搜索",
        ["ui.grid.filters"] = "筛选器",
        ["ui.grid.clear-filters"] = "清除筛选",
        ["ui.grid.columns"] = "列",
        ["ui.grid.details"] = "详情",
        ["ui.grid.page-of"] = "第 {from}–{to} 行，共 {total} 行",
        ["ui.grid.page-range"] = "第 {from}–{to} 行",
        ["ui.grid.first-page"] = "第一页",
        ["ui.grid.previous-page"] = "上一页",
        ["ui.grid.next-page"] = "下一页",
        ["ui.grid.last-page"] = "最后一页",
        ["ui.grid.select-row"] = "选择行",
        ["ui.grid.select-all"] = "选择所有行",

        ["ui.picker.today"] = "今天",
        ["ui.picker.now"] = "现在",
        ["ui.picker.clear"] = "清除",
        ["ui.picker.done"] = "完成",
        ["ui.picker.previous"] = "上一个",
        ["ui.picker.next"] = "下一个",
        ["ui.picker.hours"] = "小时",
        ["ui.picker.minutes"] = "分钟",
        ["ui.picker.seconds"] = "秒",
        ["ui.picker.meridiem"] = "上午/下午",
        ["ui.picker.start"] = "开始",
        ["ui.picker.end"] = "结束",
        ["ui.picker.open"] = "打开选择器",
        ["ui.notification.close"] = "关闭",
        ["ui.tabs.more"] = "更多标签页",
        ["ui.commandbar.more"] = "更多命令",
        ["ui.tab.close"] = "关闭",
        ["ui.tab.rename"] = "重命名",
        ["ui.tab.pin"] = "固定",
        ["ui.tab.unpin"] = "取消固定",
        ["ui.tab.delete"] = "删除",
        ["ui.select.clear"] = "清除选择",
        ["ui.select.placeholder"] = "请选择…",
        ["ui.select.remove"] = "移除 {label}",
        ["ui.input.clear"] = "清除",
        ["ui.breadcrumbs.label"] = "面包屑导航",
        ["ui.file.uploading"] = "正在上传… {percent}%",
        ["ui.file.count"] = "{count} 个文件",
        ["ui.file.failed"] = "上传失败。",
        ["ui.file.oversized"] = "文件太大。",
        ["ui.file.choose"] = "选择文件",
        ["ui.color.picker"] = "取色器",
        ["ui.color.palette"] = "调色板",
        ["ui.color.hex"] = "十六进制",
        ["ui.color.red"] = "R",
        ["ui.color.green"] = "G",
        ["ui.color.blue"] = "B",
        ["ui.color.factor"] = "系数",
        ["ui.color.opacity"] = "不透明度",
        ["ui.color.choose"] = "选择颜色",
        ["ui.splitter.label"] = "调整大小",
        ["ui.split.more"] = "更多操作",
        ["ui.image.choose"] = "选择图片",
        ["ui.image.change"] = "更换图片",
        ["ui.image.remove"] = "移除图片",
        ["ui.row.edit"] = "编辑",
        ["ui.row.save"] = "保存",
        ["ui.row.cancel"] = "取消",
        ["ui.table.resize"] = "调整列宽",
        ["ui.tree.toggle"] = "展开或折叠",
        ["ui.tree.loading"] = "正在加载…",
        ["ui.items.empty"] = "没有可显示的内容。",
        ["ui.collapse.toggle"] = "展开或折叠",
        ["ui.side.open"] = "打开侧栏",
        ["ui.menu.search"] = "搜索",
        ["ui.theme.switch"] = "切换主题",
        ["ui.language.switch"] = "切换语言，{language}",
        ["ui.notfound.title"] = "404",
        ["ui.notfound.description"] = "你要找的页面不存在。",
        ["ui.notfound.page"] = "页面不存在",
        ["ui.error.title"] = "出了点问题",
        ["ui.error.message"] = "出了点问题，请重试。",
        ["ui.command.refused"] = "你无权执行此操作。",
        ["ui.command.failed"] = "出了点问题，请重试。",
        ["ui.value.format"] = "值的格式不对。",
        ["ui.connection.lost"] = "与服务器的连接已断开。请重新加载页面以继续。",
        ["ui.connection.reload"] = "重新加载",

        ["ui.color.name.iron-fog"] = "铁雾",
        ["ui.color.name.silver-night"] = "银夜",
        ["ui.color.name.bronze-dusk"] = "青铜暮色",
        ["ui.color.name.stellar-red"] = "星红",
        ["ui.color.name.nebula-rose"] = "星云玫瑰",
        ["ui.color.name.lunar-pink"] = "月光粉",
        ["ui.color.name.solar-amber"] = "太阳琥珀",
        ["ui.color.name.nebula-gold"] = "星云金",
        ["ui.color.name.lunar-yellow"] = "月光黄",
        ["ui.color.name.eclipse-olive"] = "日食橄榄",
        ["ui.color.name.nebula-lime"] = "星云青柠",
        ["ui.color.name.lunar-sage"] = "月光鼠尾草",
        ["ui.color.name.aurora-green"] = "极光绿",
        ["ui.color.name.nebula-mint"] = "星云薄荷",
        ["ui.color.name.lunar-fern"] = "月光蕨",
        ["ui.color.name.astral-teal"] = "星青",
        ["ui.color.name.nebula-cyan"] = "星云青",
        ["ui.color.name.lunar-moss"] = "月光苔",
        ["ui.color.name.quantum-blue"] = "量子蓝",
        ["ui.color.name.nebula-aqua"] = "星云水蓝",
        ["ui.color.name.lunar-azure"] = "月光天蓝",
        ["ui.color.name.nova-purple"] = "新星紫",
        ["ui.color.name.nebula-violet"] = "星云紫罗兰",
        ["ui.color.name.lunar-lavender"] = "月光薰衣草",
        ["ui.color.name.comet"] = "彗星",
        ["ui.color.name.flare"] = "耀斑",
        ["ui.color.name.ember"] = "余烬",
        ["ui.color.name.photon"] = "光子",
        ["ui.color.name.vortex"] = "漩涡",
        ["ui.color.name.halo"] = "光环",

        ["ui.code.find"] = "查找",
        ["ui.code.replace"] = "替换",
        ["ui.code.replace-one"] = "替换",
        ["ui.code.replace-all"] = "全部替换",
        ["ui.code.toggle-replace"] = "切换替换",
        ["ui.code.previous"] = "上一个匹配",
        ["ui.code.next"] = "下一个匹配",
        ["ui.code.close"] = "关闭",
        ["ui.code.match-case"] = "区分大小写",
        ["ui.code.whole-word"] = "全字匹配",
        ["ui.code.regex"] = "正则表达式",
        ["ui.code.indentation"] = "缩进",
        ["ui.code.encoding"] = "编码",
        ["ui.code.line-ending"] = "行尾",
        ["ui.code.language"] = "语言",
        ["ui.code.plain-text"] = "纯文本",
        ["ui.code.utf8-bom"] = "UTF-8（带 BOM）",
        ["ui.code.matches"] = "第 {current} 个，共 {total} 个",
        ["ui.code.no-matches"] = "无匹配",
        ["ui.code.invalid-pattern"] = "无效的模式",
        ["ui.code.position"] = "行 {line}，列 {column}",
        ["ui.code.suggestions"] = "建议",
        ["ui.code.spaces-1"] = "1 个空格",
        ["ui.code.spaces-2"] = "2 个空格",
        ["ui.code.spaces-3"] = "3 个空格",
        ["ui.code.spaces-4"] = "4 个空格",
        ["ui.code.spaces-5"] = "5 个空格",
        ["ui.code.spaces-6"] = "6 个空格",
        ["ui.code.spaces-7"] = "7 个空格",
        ["ui.code.spaces-8"] = "8 个空格"
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Build()
        => new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal) { ["en"] = English, ["zh-Hans"] = Chinese };
}
